### ISSUE TITLE
ModuleNotFoundError: No module named 'tree'

### ISSUE THREAD

**Issue by jnoske** [RosettaCommons/RFDesign#22]
Hi,

When I want to run the script af2_metrics.py, I get the following ModuleNotFoundError:

`Traceback (most recent call last):
  File "/sw/sci/app/rfdesign/RFDesign/scripts/af2_metrics.py", line 34, in <module>
    from alphafold.common import protein
  File "/sw/sci/app/rfdesign/RFDesign/scripts/../hallucination/models/alphafold/alphafold/common/protein.py", line 19, in <module>
    from alphafold.common import residue_constants
  File "/sw/sci/app/rfdesign/RFDesign/scripts/../hallucination/models/alphafold/alphafold/common/residue_constants.py", line 22, in <module>
    import tree
ModuleNotFoundError: No module named 'tree'`

The environment was set up from the .yml, but I looks like this module is not included.

Best,
Jakob

**Comment by jueseph** [comment]
Sorry, not sure why this isn't in the environment yaml.

Easiest is probably just to install it yourself: pip install dm-tree

**Comment by jnoske** [comment]
Thanks a lot that was missing.
