### ISSUE TITLE
checkpoint file not found problem about inpaint

### ISSUE THREAD

**Issue by yx0516** [RosettaCommons/RFDesign#3]
Hi, developers

i am trying to run test in inpaint and i got the following problem:
Where can i find the folder and file "envsjwatson3_first_full_epoch/BFF_epoch_0_fraction_1.0.pt"
Thanks a lot.

Loading checkpoint v02: /home/yanx/Dev/repos/RFDesign/envsjwatson3_first_full_epoch/BFF_epoch_0_fraction_1.0.pt...
Traceback (most recent call last):
  File "../inpaint.py", line 837, in <module>
    main()
  File "../inpaint.py", line 375, in main
    ckpt = torch.load(cp_path, map_location=DEVICE)
  File "/home/yanx/.conda/envs/se3test/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yanx/.conda/envs/se3test/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yanx/.conda/envs/se3test/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/yanx/Dev/repos/RFDesign/envsjwatson3_first_full_epoch/BFF_epoch_0_fraction_1.0.pt'

**Comment by jueseph** [comment]
You need an additional forward slash at the end of the --weights_dir
argument. It looks like you've specified this as
/home/yanx/Dev/repos/RFDesign/envs. Is that where you've put the weights?
If it is then adding a forward slash to the end should work. If not, then
you should provide the --weights_dir argument with the path to the weights
or include this in a config.json file in the inpaint/ folder.

**Comment by yx0516** [comment]
I have put an additional forward slash in the file config.json:
"weights_dir": "/home/yanx/Dev/repos/RFDesign/envs/"

However i still got the problem:
Loading checkpoint v02: /home/yanx/Dev/repos/RFDesign/envs/jwatson3_first_full_epoch/BFF_epoch_0_fraction_1.0.pt...
Traceback (most recent call last):
  File "../inpaint.py", line 837, in <module>
    main()
  File "../inpaint.py", line 375, in main
    ckpt = torch.load(cp_path, map_location=DEVICE)
  File "/home/yanx/.conda/envs/se3test/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yanx/.conda/envs/se3test/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yanx/.conda/envs/se3test/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/yanx/Dev/repos/RFDesign/envs/jwatson3_first_full_epoch/BFF_epoch_0_fraction_1.0.pt'

**Comment by jueseph** [comment]
Did you download the weights into that folder?

**Comment by yx0516** [comment]
I have fixed the problem. Thanks a lot
