### ISSUE TITLE
Hallucination w/ receptor crashing while saving output

### ISSUE THREAD

**Issue by Paulther** [RosettaCommons/RFDesign#32]
Hi,
I have been trying to hallucinate some new designs to bind a particular target. The hallucination script crashes while trying to save the output.
**Input command:**
python hallucinate.py --pdb antiIL6_shorter_bound.pdb --contigs=A32-33,A55-58,A103-106,A170,A174-178,A212-213,A239-240 --force_aa=A32-33,A55-58,A103-106,A170,A174-178,A212-213,A239-240 --len=125-150 --receptor IL6_Ligand_Shortened_Alpha_CB.pdb --out IL6/IL6 --num=200 --steps=g10 --exclude_aa C --save_pdb=True

**Output:**
Using CUDA device(s):  cuda:0: (NVIDIA GeForce RTX 3080); 

Parsing input pdb...
Parsing receptor pdb...

Generating IL6_0, length 201...
Forcing amino acids:  A32R,A33Y,A55Y,A56D,A57G,A58D,A103V,A104V,A105T,A106G,A170N,A174G,A175T,A176Y,A177A,A178Y,A212K,A213S,A239N,A240F, and 61 receptor positions
Calculating 100 background distributions...
Loss term           | Weight      
cce                   1.00
entropy               1.00
kl                    1.00

Stage 0
Starting gradient descent...
        step    avg loss         cce     entropy          kl
           0      2.7400      5.0881      3.2141     -0.0821
          10      2.5137      4.5615      3.0856     -0.1060
       final      2.4549      4.3876      3.1224     -0.1454
best loss step: 1
Max CUDA memory: 6.4923G
Saving /home/paul/RFDesign/hallucination/IL6/IL6_0: Traceback (most recent call last):
  File "/home/paul/RFDesign/hallucination/hallucinate.py", line 739, in <module>
    main()
  File "/home/paul/RFDesign/hallucination/hallucinate.py", line 731, in main
    optimization.save_result(out_prefix, Net, ml, trb['msa'], args, trb, 
  File "/home/paul/RFDesign/hallucination/util/../optimization.py", line 179, in save_result
    idx_tmpl = net_kwargs['idx'].cpu().numpy()[0]
KeyError: 'idx'

Any idea what the problem is?

**Comment by geraseva** [comment]
Same problem

**Comment by geraseva** [comment]
Perhaps this would be helpful https://github.com/RosettaCommons/RFDesign/issues/9
