### ISSUE TITLE
Multiple ModuleNotFoundError

### ISSUE THREAD

**Issue by kierandidi** [RosettaCommons/RFDesign#33]
Hi,

similar to issue 22, when I want to run the script af2_metrics.py, I get the following ModuleNotFoundError:

```
Traceback (most recent call last):
  File "/home/kieran/RFDesign/hallucination/tests/../../scripts/af2_metrics.py", line 34, in <module>
    from alphafold.common import protein
  File "/home/kieran/RFDesign/scripts/../hallucination/models/alphafold/alphafold/common/protein.py",
   line 20, in <module>
    from Bio.PDB import PDBParser
ModuleNotFoundError: No module named 'Bio'
```

I also had the tree error from issue 22 before, but this one popped up after I installed tree. 

I solved it by running `pip install biopython`, but for reproducibility, it might be useful to include biopython in the environment file.

After that got another one: 

```
  File "/home/kieran/RFDesign/hallucination/tests/../../scripts/af2_metrics.py", line 35, in <module>
    from alphafold.data import pipeline
  File "/home/kieran/RFDesign/scripts/../hallucination/models/alphafold/alphafold/data/pipeline.py",
   line 19, in <module>
    from absl import logging
ModuleNotFoundError: No module named 'absl'
```
Fixed this one via `pip install absl-py`. If I am correct this was not included in the .yaml file either right?

A third one: 
```
Traceback (most recent call last):
  File "/home/kieran/RFDesign/hallucination/tests/../../scripts/af2_metrics.py", line 37, in <module>
    from alphafold.model import data
  File "/home/kieran/RFDesign/scripts/../hallucination/models/alphafold/alphafold/model/data.py", line 20, in <module>
    from alphafold.model import utils
  File "/home/kieran/RFDesign/scripts/../hallucination/models/alphafold/alphafold/model/utils.py", line 21, in <module>
    import haiku as hk
ModuleNotFoundError: No module named 'haiku'
```

After that quite a few others came up (fixes listed below): 

- pip install dm-haiku
- pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
(from: https://github.com/google/jax#installation)
- pip install ml-collections
- pip install tensorflow
- conda install -c conda-forge pdbfixer
- pip install torch

Currently I get the error `ModuleNotFoundError: No module named 'simtk.openmm.app.internal'`.

Before I continue down the rabbit hole: did I miss some installation files here or are these dependencies just not documented?

All the best,
Kieran

**Comment by kierandidi** [comment]
Found Issue #26 and #27, so that is that. But would be amazing if the team could update the README to reflect these points. Thanks again for making all this available!
