### ISSUE TITLE
Issue with alphafold-complex predication with initial guess of binder position

### ISSUE THREAD

**Issue by QILINY** [RosettaCommons/RFDesign#38]
I got the following error messages when running af2_interface_metrics.py

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../../../../../scripts/af2_interface_metrics.py", line 600, in <module>
    predict_structure(tag_buffer, feature_dict_dict, binderlen_dict, initial_guess_dict, sfd_out, scorefilename)
  File "../../../../../../scripts/af2_interface_metrics.py", line 429, in predict_structure
    prediction_result = jax.vmap(model_runner.apply, in_axes=(None,None,0,0))(model_runner.params, jax.random.PRNGKey(0), processed_feature_dict, processed_initial_guess_dict)
  File "/HOME/scz3220/.conda/envs/rfdesign/lib/python3.8/site-packages/haiku/_src/transform.py", line 127, in apply_fn
    out, state = f.apply(params, {}, *args, **kwargs)
  File "/HOME/scz3220/.conda/envs/rfdesign/lib/python3.8/site-packages/haiku/_src/transform.py", line 354, in apply_fn
    out = f(*args, **kwargs)
TypeError: _forward_fn() takes 1 positional argument but 2 were given
```

it seems like the current version of alphafold attached in this directory hallucination/models/alphafold/alphafold/ is not compatible with the scripts af2_interface_metrics.py.

May I ask how to modify alphafold scripts to pass initial guess of binders' position? Thanks for sharing this great work! and best wishes~

**Comment by aravinda1879** [comment]
Did you find a solution for this? I am having the same issue and I wonder if you found a solution.

**Comment by jueseph** [comment]
see my reply in https://github.com/RosettaCommons/RFDesign/issues/48
