### ISSUE TITLE
no PDBs output/NameError: name 'aa_util' is not defined

### ISSUE THREAD

**Issue by morin-andrew** [RosettaCommons/RFDesign#51]
I'm getting en error where the runs says it completes successfully, but wont output any pdb files. 

Example:

>python /home/ubuntu/RFDesign/inpainting/inpaint.py --pdb test_linker.pdb --contigs A1-133,0 B134-316,45,B347-553 --out out/45_test --num_designs 1
```
ic| args: Namespace(pdb='/home/ubuntu/inpaint_test/test_linker.pdb', contigs=['A1-133,0', 'B134-316,31,B347-553'], length=None, checkpoint='/home/ubuntu/RFDesign/inpainting/weights/BFF_mix_epoch25.pt', inpaint_str=None, inpaint_seq=None, n_cycle=4, tmpl_conf='0.5', num_designs=1, res_translate=None, tie_translate=None, floating_points=None, block_rotate=None, verbose=False, out='/home/ubuntu/inpaint_test', dump_pdb=True, dump_trb=False, dump_npz=False, dump_fasta=False, dump_all=False, input_json=None, outdir='/home/ubuntu', prefix='inpaint_test')
On design  0
ic| args.contigs: ['A1-133,0', 'B134-316,31,B347-553']
on cycle 0
on cycle 1
on cycle 2
Successfully wrote output
```

If I run with the "--verbose" flag, it yields the following:

>python /home/ubuntu/RFDesign/inpainting/inpaint.py --pdb test_linker.pdb --contigs A1-133,0 B134-316,45,B347-553 --out out/45_test --num_designs 1 --dump_all --verbose
```
ic| args: Namespace(pdb='test_linker.pdb', contigs=['A1-133,0', 'B134-316,45,B347-553'], length=None, checkpoint='/home/ubuntu/RFDesign/inpainting/weights/BFF_mix_epoch25.pt', inpaint_str=None, inpaint_seq=None, n_cycle=4, tmpl_conf='0.5', num_designs=1, res_translate=None, tie_translate=None, floating_points=None, block_rotate=None, verbose=True, out='out/45_test', dump_pdb=True, dump_trb=True, dump_npz=True, dump_fasta=True, dump_all=True, input_json=None, outdir='out', prefix='45_test')
On design  0
ic| args.contigs: ['A1-133,0', 'B134-316,45,B347-553']
Traceback (most recent call last):
  File "/home/ubuntu/RFDesign/inpainting/inpaint.py", line 435, in <module>
    main()
  File "/home/ubuntu/RFDesign/inpainting/inpaint.py", line 346, in main
    ic(aa_util.seq2chars(seq))
NameError: name 'aa_util' is not defined
```

I should also mention that the inpainting tests cmplete successfully and so output a pdb.
Any ideas or pointers would be appreciated. 

-Andrew

**Comment by JinyuanSun** [comment]
The same error.

**Comment by jueseph** [comment]
Not sure what's going on here, but the inpainting method in this repository is actually quite old at this point. RFDiffusion was just released today -- it is much better. You should probably just use that for whatever design problem you are trying. I think the code is also a little better documented / less buggy, as well. https://github.com/RosettaCommons/RFdiffusion

**Comment by morin-andrew** [comment]
RFdiffusion released today! Awesome. Thanks for the heads up.
